/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUserRouteImport } from './routes/app/user'
import { Route as AdminUserRouteImport } from './routes/admin/user'
import { Route as AppSystemRouteRouteImport } from './routes/app/system/route'
import { Route as AppSystemRoleRouteImport } from './routes/app/system/role'
import { Route as AppSystemPermissionRouteImport } from './routes/app/system/permission'
import { Route as AppSystemModuleRouteImport } from './routes/app/system/module'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserRoute = AppUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminUserRoute = AdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppSystemRouteRoute = AppSystemRouteRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSystemRoleRoute = AppSystemRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AppSystemRouteRoute,
} as any)
const AppSystemPermissionRoute = AppSystemPermissionRouteImport.update({
  id: '/permission',
  path: '/permission',
  getParentRoute: () => AppSystemRouteRoute,
} as any)
const AppSystemModuleRoute = AppSystemModuleRouteImport.update({
  id: '/module',
  path: '/module',
  getParentRoute: () => AppSystemRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/system': typeof AppSystemRouteRouteWithChildren
  '/admin/user': typeof AdminUserRoute
  '/app/user': typeof AppUserRoute
  '/app/system/module': typeof AppSystemModuleRoute
  '/app/system/permission': typeof AppSystemPermissionRoute
  '/app/system/role': typeof AppSystemRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/system': typeof AppSystemRouteRouteWithChildren
  '/admin/user': typeof AdminUserRoute
  '/app/user': typeof AppUserRoute
  '/app/system/module': typeof AppSystemModuleRoute
  '/app/system/permission': typeof AppSystemPermissionRoute
  '/app/system/role': typeof AppSystemRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/system': typeof AppSystemRouteRouteWithChildren
  '/admin/user': typeof AdminUserRoute
  '/app/user': typeof AppUserRoute
  '/app/system/module': typeof AppSystemModuleRoute
  '/app/system/permission': typeof AppSystemPermissionRoute
  '/app/system/role': typeof AppSystemRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/app/system'
    | '/admin/user'
    | '/app/user'
    | '/app/system/module'
    | '/app/system/permission'
    | '/app/system/role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/app/system'
    | '/admin/user'
    | '/app/user'
    | '/app/system/module'
    | '/app/system/permission'
    | '/app/system/role'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/app/system'
    | '/admin/user'
    | '/app/user'
    | '/app/system/module'
    | '/app/system/permission'
    | '/app/system/role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/user': {
      id: '/app/user'
      path: '/user'
      fullPath: '/app/user'
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/system': {
      id: '/app/system'
      path: '/system'
      fullPath: '/app/system'
      preLoaderRoute: typeof AppSystemRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/system/role': {
      id: '/app/system/role'
      path: '/role'
      fullPath: '/app/system/role'
      preLoaderRoute: typeof AppSystemRoleRouteImport
      parentRoute: typeof AppSystemRouteRoute
    }
    '/app/system/permission': {
      id: '/app/system/permission'
      path: '/permission'
      fullPath: '/app/system/permission'
      preLoaderRoute: typeof AppSystemPermissionRouteImport
      parentRoute: typeof AppSystemRouteRoute
    }
    '/app/system/module': {
      id: '/app/system/module'
      path: '/module'
      fullPath: '/app/system/module'
      preLoaderRoute: typeof AppSystemModuleRouteImport
      parentRoute: typeof AppSystemRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminUserRoute: typeof AdminUserRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUserRoute: AdminUserRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppSystemRouteRouteChildren {
  AppSystemModuleRoute: typeof AppSystemModuleRoute
  AppSystemPermissionRoute: typeof AppSystemPermissionRoute
  AppSystemRoleRoute: typeof AppSystemRoleRoute
}

const AppSystemRouteRouteChildren: AppSystemRouteRouteChildren = {
  AppSystemModuleRoute: AppSystemModuleRoute,
  AppSystemPermissionRoute: AppSystemPermissionRoute,
  AppSystemRoleRoute: AppSystemRoleRoute,
}

const AppSystemRouteRouteWithChildren = AppSystemRouteRoute._addFileChildren(
  AppSystemRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppSystemRouteRoute: typeof AppSystemRouteRouteWithChildren
  AppUserRoute: typeof AppUserRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSystemRouteRoute: AppSystemRouteRouteWithChildren,
  AppUserRoute: AppUserRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
