/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserListRouteImport } from './routes/user-list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SysManageRouteRouteImport } from './routes/sys-manage/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SysManageUserRouteImport } from './routes/sys-manage/user'
import { Route as SysManageRoleRouteImport } from './routes/sys-manage/role'

const UserListRoute = UserListRouteImport.update({
  id: '/user-list',
  path: '/user-list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SysManageRouteRoute = SysManageRouteRouteImport.update({
  id: '/sys-manage',
  path: '/sys-manage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SysManageUserRoute = SysManageUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => SysManageRouteRoute,
} as any)
const SysManageRoleRoute = SysManageRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => SysManageRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sys-manage': typeof SysManageRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/user-list': typeof UserListRoute
  '/sys-manage/role': typeof SysManageRoleRoute
  '/sys-manage/user': typeof SysManageUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sys-manage': typeof SysManageRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/user-list': typeof UserListRoute
  '/sys-manage/role': typeof SysManageRoleRoute
  '/sys-manage/user': typeof SysManageUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sys-manage': typeof SysManageRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/user-list': typeof UserListRoute
  '/sys-manage/role': typeof SysManageRoleRoute
  '/sys-manage/user': typeof SysManageUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sys-manage'
    | '/login'
    | '/user-list'
    | '/sys-manage/role'
    | '/sys-manage/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sys-manage'
    | '/login'
    | '/user-list'
    | '/sys-manage/role'
    | '/sys-manage/user'
  id:
    | '__root__'
    | '/'
    | '/sys-manage'
    | '/login'
    | '/user-list'
    | '/sys-manage/role'
    | '/sys-manage/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SysManageRouteRoute: typeof SysManageRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  UserListRoute: typeof UserListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-list': {
      id: '/user-list'
      path: '/user-list'
      fullPath: '/user-list'
      preLoaderRoute: typeof UserListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sys-manage': {
      id: '/sys-manage'
      path: '/sys-manage'
      fullPath: '/sys-manage'
      preLoaderRoute: typeof SysManageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sys-manage/user': {
      id: '/sys-manage/user'
      path: '/user'
      fullPath: '/sys-manage/user'
      preLoaderRoute: typeof SysManageUserRouteImport
      parentRoute: typeof SysManageRouteRoute
    }
    '/sys-manage/role': {
      id: '/sys-manage/role'
      path: '/role'
      fullPath: '/sys-manage/role'
      preLoaderRoute: typeof SysManageRoleRouteImport
      parentRoute: typeof SysManageRouteRoute
    }
  }
}

interface SysManageRouteRouteChildren {
  SysManageRoleRoute: typeof SysManageRoleRoute
  SysManageUserRoute: typeof SysManageUserRoute
}

const SysManageRouteRouteChildren: SysManageRouteRouteChildren = {
  SysManageRoleRoute: SysManageRoleRoute,
  SysManageUserRoute: SysManageUserRoute,
}

const SysManageRouteRouteWithChildren = SysManageRouteRoute._addFileChildren(
  SysManageRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SysManageRouteRoute: SysManageRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  UserListRoute: UserListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
