import {
  BadgeDollarSign,
  Bell,
  Book,
  Check,
  ChevronDown,
  ChevronRight,
  CreditCard,
  Edit,
  FileText,
  Fingerprint,
  Home,
  Layers,
  LayoutDashboard,
  LogOut,
  Menu,
  MoreHorizontal,
  PieChart,
  Plus,
  Save,
  Search,
  Settings,
  Shield,
  Tag,
  Trash,
  User,
  Users,
  X,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

export const iconMap: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  settings: Settings,
  users: Users,
  shield: Shield,
  menu: Menu,
  home: Home,
  "file-text": FileText,
  "credit-card": CreditCard,
  "pie-chart": PieChart,
  user: User,
  logout: LogOut,
  bell: Bell,
  search: Search,
  plus: Plus,
  trash: Trash,
  edit: Edit,
  save: Save,
  x: X,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "more-horizontal": MoreHorizontal,
  "badge-dollar-sign": BadgeDollarSign,
  book: Book,
  tag: Tag,
  layers: Layers,
  fingerprint: Fingerprint,
}

export function getIcon(name: string) {
  const Icon = iconMap[name]
  return Icon ? <Icon size={18} /> : <Menu size={18} />
}
