import { type ThemeConfig, theme } from "antd"

const lightTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: "#18181b",
    colorSuccess: "#16a34a",
    colorWarning: "#d97706",
    colorError: "#dc2626",
    colorInfo: "#18181b",
    colorTextBase: "#18181b",
    colorBgBase: "#fafafa",
    colorPrimaryBg: "#f4f4f5",
    colorPrimaryBgHover: "#e4e4e7",
    colorPrimaryBorder: "#a1a1aa",
    colorPrimaryBorderHover: "#71717a",
    colorPrimaryHover: "#27272a",
    colorPrimaryActive: "#09090b",
    colorPrimaryText: "#18181b",
    colorPrimaryTextHover: "#27272a",
    colorPrimaryTextActive: "#09090b",
    colorSuccessBg: "#f0fdf4",
    colorSuccessBgHover: "#dcfce7",
    colorSuccessBorder: "#86efac",
    colorSuccessBorderHover: "#4ade80",
    colorSuccessHover: "#15803d",
    colorSuccessActive: "#14532d",
    colorSuccessText: "#16a34a",
    colorSuccessTextHover: "#15803d",
    colorSuccessTextActive: "#14532d",
    colorWarningBg: "#fffbeb",
    colorWarningBgHover: "#fef3c7",
    colorWarningBorder: "#fcd34d",
    colorWarningBorderHover: "#fbbf24",
    colorWarningHover: "#b45309",
    colorWarningActive: "#78350f",
    colorWarningText: "#d97706",
    colorWarningTextHover: "#b45309",
    colorWarningTextActive: "#78350f",
    colorErrorBg: "#fef2f2",
    colorErrorBgHover: "#fee2e2",
    colorErrorBorder: "#fca5a5",
    colorErrorBorderHover: "#f87171",
    colorErrorHover: "#b91c1c",
    colorErrorActive: "#7f1d1d",
    colorErrorText: "#dc2626",
    colorErrorTextHover: "#b91c1c",
    colorErrorTextActive: "#7f1d1d",
    colorInfoBg: "#f4f4f5",
    colorInfoBgHover: "#e4e4e7",
    colorInfoBorder: "#a1a1aa",
    colorInfoBorderHover: "#71717a",
    colorInfoHover: "#27272a",
    colorInfoActive: "#09090b",
    colorInfoText: "#18181b",
    colorInfoTextHover: "#27272a",
    colorInfoTextActive: "#09090b",
    colorText: "#18181b",
    colorTextSecondary: "#3f3f46",
    colorTextTertiary: "#71717a",
    colorTextQuaternary: "#a1a1aa",
    colorTextDisabled: "#a1a1aa",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBgLayout: "#fafafa",
    colorBgSpotlight: "#18181b",
    colorBgMask: "rgba(0, 0, 0, 0.45)",
    colorBorder: "#e4e4e7",
    colorBorderSecondary: "#f4f4f5",
    borderRadius: 6,
    borderRadiusXS: 2,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)",
    boxShadowSecondary: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)",
  },
}

const darkTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary: "#fafafa",
    colorSuccess: "#22c55e",
    colorWarning: "#f59e0b",
    colorError: "#ef4444",
    colorInfo: "#fafafa",
    colorTextBase: "#fafafa",
    colorBgBase: "#09090b",
    colorPrimaryBg: "#27272a",
    colorPrimaryBgHover: "#3f3f46",
    colorPrimaryBorder: "#52525b",
    colorPrimaryBorderHover: "#71717a",
    colorPrimaryHover: "#f4f4f5",
    colorPrimaryActive: "#e4e4e7",
    colorPrimaryText: "#fafafa",
    colorPrimaryTextHover: "#f4f4f5",
    colorPrimaryTextActive: "#e4e4e7",
    colorSuccessBg: "#14532d",
    colorSuccessBgHover: "#166534",
    colorSuccessBorder: "#15803d",
    colorSuccessBorderHover: "#16a34a",
    colorSuccessHover: "#4ade80",
    colorSuccessActive: "#22c55e",
    colorSuccessText: "#86efac",
    colorSuccessTextHover: "#bbf7d0",
    colorSuccessTextActive: "#dcfce7",
    colorWarningBg: "#451a03",
    colorWarningBgHover: "#713f12",
    colorWarningBorder: "#b45309",
    colorWarningBorderHover: "#92400e",
    colorWarningHover: "#fbbf24",
    colorWarningActive: "#d97706",
    colorWarningText: "#fbbf24",
    colorWarningTextHover: "#f59e0b",
    colorWarningTextActive: "#d97706",
    colorErrorBg: "#450a0a",
    colorErrorBgHover: "#7f1d1d",
    colorErrorBorder: "#b91c1c",
    colorErrorBorderHover: "#991b1b",
    colorErrorHover: "#f87171",
    colorErrorActive: "#dc2626",
    colorErrorText: "#f87171",
    colorErrorTextHover: "#ef4444",
    colorErrorTextActive: "#dc2626",
    colorInfoBg: "#27272a",
    colorInfoBgHover: "#3f3f46",
    colorInfoBorder: "#52525b",
    colorInfoBorderHover: "#71717a",
    colorInfoHover: "#f4f4f5",
    colorInfoActive: "#e4e4e7",
    colorInfoText: "#fafafa",
    colorInfoTextHover: "#f4f4f5",
    colorInfoTextActive: "#e4e4e7",
    colorText: "#fafafa",
    colorTextSecondary: "#a1a1aa",
    colorTextTertiary: "#71717a",
    colorTextQuaternary: "#52525b",
    colorTextDisabled: "#52525b",
    colorBgContainer: "#09090b",
    colorBgElevated: "#18181b",
    colorBgLayout: "#09090b",
    colorBgSpotlight: "#27272a",
    colorBgMask: "rgba(0, 0, 0, 0.6)",
    colorBorder: "#27272a",
    colorBorderSecondary: "#27272a",
    borderRadius: 6,
    borderRadiusXS: 2,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    boxShadow: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
    boxShadowSecondary: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
  },
}

const commonComponents = {
  Layout: {
    headerPadding: "0 24px",
  },
  Menu: {
    activeBarBorderWidth: 0,
    itemBorderRadius: 6,
    collapsedWidth: 63,
  },
  Table: {
    borderRadius: 8,
  },
  Card: {
    borderRadius: 8,
  },
}

export const themes = {
  light: {
    ...lightTheme,
    components: {
      ...commonComponents,
      Button: {
        primaryColor: "#ffffff", // Light mode primary text (White on Dark)
      },
    },
  },
  dark: {
    ...darkTheme,
    components: {
      ...commonComponents,
      Button: {
        primaryColor: "#18181b", // Dark mode primary text (Dark on Light)
      },
    },
  },
}
